[build]
  command = "npm run build"
  publish = ".output/public"

[functions]
  node_bundler = "esbuild"

# TanStack Start / Nitro / Vinxi on Netlify
# This ensures that all requests are handled by the SSR server function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  NITRO_PRESET = "netlify"
