/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSurveyRouteImport } from './routes/_app/survey'
import { Route as AppResultsRouteImport } from './routes/_app/results'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as SurveyPublicIdRouteImport } from './routes/survey/public/$id'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminSurveysRouteImport } from './routes/_app/admin/surveys'
import { Route as AppAdminQuestionsRouteImport } from './routes/_app/admin/questions'
import { Route as AppAdminDepartmentsRouteImport } from './routes/_app/admin/departments'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSurveyRoute = AppSurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const SurveyPublicIdRoute = SurveyPublicIdRouteImport.update({
  id: '/survey/public/$id',
  path: '/survey/public/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSurveysRoute = AppAdminSurveysRouteImport.update({
  id: '/admin/surveys',
  path: '/admin/surveys',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminQuestionsRoute = AppAdminQuestionsRouteImport.update({
  id: '/admin/questions',
  path: '/admin/questions',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDepartmentsRoute = AppAdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/results': typeof AppResultsRoute
  '/survey': typeof AppSurveyRoute
  '/admin/departments': typeof AppAdminDepartmentsRoute
  '/admin/questions': typeof AppAdminQuestionsRoute
  '/admin/surveys': typeof AppAdminSurveysRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/survey/public/$id': typeof SurveyPublicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/results': typeof AppResultsRoute
  '/survey': typeof AppSurveyRoute
  '/admin/departments': typeof AppAdminDepartmentsRoute
  '/admin/questions': typeof AppAdminQuestionsRoute
  '/admin/surveys': typeof AppAdminSurveysRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/survey/public/$id': typeof SurveyPublicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/results': typeof AppResultsRoute
  '/_app/survey': typeof AppSurveyRoute
  '/_app/admin/departments': typeof AppAdminDepartmentsRoute
  '/_app/admin/questions': typeof AppAdminQuestionsRoute
  '/_app/admin/surveys': typeof AppAdminSurveysRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/survey/public/$id': typeof SurveyPublicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/login'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/results'
    | '/survey'
    | '/admin/departments'
    | '/admin/questions'
    | '/admin/surveys'
    | '/admin/users'
    | '/survey/public/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/login'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/results'
    | '/survey'
    | '/admin/departments'
    | '/admin/questions'
    | '/admin/surveys'
    | '/admin/users'
    | '/survey/public/$id'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/results'
    | '/_app/survey'
    | '/_app/admin/departments'
    | '/_app/admin/questions'
    | '/_app/admin/surveys'
    | '/_app/admin/users'
    | '/survey/public/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SurveyPublicIdRoute: typeof SurveyPublicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/survey': {
      id: '/_app/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof AppSurveyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/results': {
      id: '/_app/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/survey/public/$id': {
      id: '/survey/public/$id'
      path: '/survey/public/$id'
      fullPath: '/survey/public/$id'
      preLoaderRoute: typeof SurveyPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/surveys': {
      id: '/_app/admin/surveys'
      path: '/admin/surveys'
      fullPath: '/admin/surveys'
      preLoaderRoute: typeof AppAdminSurveysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/questions': {
      id: '/_app/admin/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AppAdminQuestionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/departments': {
      id: '/_app/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AppAdminDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResultsRoute: typeof AppResultsRoute
  AppSurveyRoute: typeof AppSurveyRoute
  AppAdminDepartmentsRoute: typeof AppAdminDepartmentsRoute
  AppAdminQuestionsRoute: typeof AppAdminQuestionsRoute
  AppAdminSurveysRoute: typeof AppAdminSurveysRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppResultsRoute: AppResultsRoute,
  AppSurveyRoute: AppSurveyRoute,
  AppAdminDepartmentsRoute: AppAdminDepartmentsRoute,
  AppAdminQuestionsRoute: AppAdminQuestionsRoute,
  AppAdminSurveysRoute: AppAdminSurveysRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SurveyPublicIdRoute: SurveyPublicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
